[package]
name = "bombon-transformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
cyclonedx-bom = "0.4.0"
itertools = "0.10.5"
serde = { version = "1.0.151", features = [ "derive" ] }
serde_json = "1.0.89"
