[package]
name = "bombon-transformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
cyclonedx-bom = "0.3.5"
itertools = "0.10.5"
serde = { version = "1.0.145", features = [ "derive" ] }
serde_json = "1.0.85"

[patch.crates-io]
cyclonedx-bom = { git = "https://github.com/nikstur/cyclonedx-rust-cargo", branch = "add-public-interfaces"  }
