name: "Update Nix dependencies"

on:
  schedule:
    # Run on the 2nd of every month at 04:04
    # This should avoid spikes in usage caused by other scheduled jobs
    - cron: "4 4 2 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v6
      - uses: samueldr/lix-gha-installer-action@v2025-10-27
      - env:
          LON_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LON_LABELS: "lon,bot"
          LON_LIST_COMMITS: 10
        run: nix-shell nix/ci-shell.nix --run "lon -vv bot github"

env:
  FORCE_COLOR: 1
